language: java
sudo: false

jdk:
  - openjdk11

services:
  - docker

script:
  - cd ./docker
  - chmod +x docker_build_and_run.sh && ./docker_build_and_run.sh
  - sleep 30
  - curl -f http://localhost:8080/actuator/health