apiVersion: v1
kind: Service
metadata:
  name: sbda-app-service
  labels:
    name: sbda-app-service
    app: sbda-app
spec:          
  type: NodePort
  ports:
  - targetPort: 8080
    port: 8080
    nodePort: 30100
  selector:
    name: sbda-app-pod
    app: sbda-app